name: Keepalive Workflow

on:
  schedule:
    # 每天 UTC 时间 00:00 运行一次
    - cron: "0 0 * * *"

permissions:
  actions: write

jobs:
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/keepalive-workflow@v2
